Fixing the rvm install script

diff --git a/rvm-install-head b/rvm-install-head
--- a/rvm-install-head
+++ b/rvm-install-head
@@ -1,5 +1,11 @@
 #!/bin/env bash
 
+shopt -s extglob
+PS4="+ \${BASH_SOURCE##\${rvm_path:-}} : \${FUNCNAME[0]:+\${FUNCNAME[0]}()}  \${LINENO} > "
+export PS4
+set -o errtrace
+set -o errexit
+
 log()  { printf "$*\n" ; return $? ;  }
 
 fail() { log "\nERROR: $*\n" ; exit 1 ; }
@@ -27,12 +33,12 @@ Actions
 
 fetch_version()
 {
-  version=$(curl -B "${rvm_releases_url}/latest-version.txt" 2>/dev/null)
+  version=$(curl -s -B "${rvm_releases_url}/latest-version.txt" 2>/dev/null)
 }
 
 fetch_md5()
 {
-  md5=$(curl -B "${rvm_releases_url}/rvm-${version}.tar.gz.md5" 2>/dev/null)
+  md5=$(curl -s -B "${rvm_releases_url}/rvm-${version}.tar.gz.md5" 2>/dev/null)
 }
 
 md5_match()
@@ -49,33 +55,49 @@ md5_match()
       ;;
 
     Linux|*)
-      archive_md5="$(md5sum "${archive}" | awk '{print $1}')"
+      archive_md5="$(md5sum "${archive}")"
+      archive_md5="${archive_md5%% *}"
       ;;
   esac
 
-  [[ "$archive_md5" == "$md5" ]]
-
-  return $?
+  if [[ "$archive_md5" == "$md5" ]]
+  then
+    return 0
+  else
+    return 1
+  fi
 }
 
 install_release()
 {
-  archive="$rvm_archives_path/rvm-${version}.tar.gz"
+  local archive url
+
+  archive="${rvm_archives_path}/rvm-${version}.tar.gz"
+  url="${rvm_releases_url}/rvm-${version}.tar.gz"
 
   fetch_md5
 
-  if [[ -s $archive ]] && ! md5_match ; then
+  if [[ -s "${archive}" && -n "${md5}" ]] && ! md5_match "${archive}"
+  then
     # Remove old installs, if they exist and have incorrect md5.
-    [[ -f "$rvm_archives_path/rvm-${version}.tar.gz" ]] &&
-      rm -f "$rvm_archives_path/rvm-${version}.tar.gz"
+    if [[ -f "${archive}" ]]
+    then
+      rm -f "${archive}"
+    fi
   fi
 
-  curl -L "${rvm_releases_url}/rvm-${version}.tar.gz" -o "$archive"
+  if curl -L "${url}" -o "${archive}"
+  then
+    true
+  else
+    fail "Failed to download ${url} to ${archive} using 'curl', error code ($?)"
+  fi
 
-  if ! md5_match "$archive" ; then
+  if ! md5_match "$archive"
+  then
     fail "ERROR:
 
-Archive package downloaded does not match it's calculated md5 checksum ${md5}:
+Archive package downloaded does not match its calculated md5 checksum ${md5}:
 
   $rvm_archives_path/rvm-${version}.tar.gz
 
@@ -85,34 +107,54 @@ Halting installation.
 "
   fi
 
-  tar zxf "${rvm_archives_path}/rvm-${version}.tar.gz" -C "$rvm_src_path/" --no-same-owner
-
-  cd "$rvm_src_path/rvm-${version}"
+  if tar zxf "${archive}" -C "$rvm_src_path/" --no-same-owner
+  then
+    cd "$rvm_src_path/rvm-${version}"
+  else
+    fail "Failed to extract ${archive} to ${rvm_src_path}/,"\
+      "tar command returned error code $?"
+  fi
 }
 
 install_head()
 {
   local remote="origin"
 
-  if [[ -d "${rvm_src_path}/rvm/.git" ]] ; then
+  if [[ -d "${rvm_src_path}/rvm/.git" ]]
+  then
     builtin cd "${rvm_src_path}/rvm/"
 
-    if [[ -z "$(git branch | awk "/$branch$/")" ]] ; then
-      if ! git checkout -b "$branch" --track "$remote/$branch" 2>/dev/null ; then
+    if [[ -z "$(git branch | awk "/$branch$/")" ]]
+    then
+      if git checkout -b "$branch" --track "$remote/$branch" 2>/dev/null
+      then
+        log "Successfully checked out branch '$branch'"
+      else
         fail "$remote $branch remote branch not found."
       fi
-    elif [[ -z "$(git branch | awk "/\* $branch$/{print \$2}")" ]] ; then
-      if ! git checkout $branch 2>/dev/null ; then
-        fail "Unable to checkout $branch."
+    elif [[ -z "$(git branch | awk "/\* $branch$/{print \$2}")" ]]
+    then
+      if git checkout $branch 2>/dev/null
+      then
+        log "Successfully checked out branch '$branch'"
+      else
+        fail "Unable to checkout branch $branch."
       fi
     fi
 
-    git pull --rebase origin $branch
+    if git pull --rebase $remote $branch
+    then
+      log "Successfully pulled (rebased) from $remote $branch"
+    else
+      fail "Failed pull/rebase $remote $branch"
+    fi
   else
     builtin cd "${rvm_src_path}"
 
-    if ! git clone --depth 1 git://github.com/wayneeseguin/rvm.git ; then
-      if !  git clone https://github.com/wayneeseguin/rvm.git ; then
+    if ! git clone --depth 1 git://github.com/wayneeseguin/rvm.git
+    then
+      if !  git clone https://github.com/wayneeseguin/rvm.git
+      then
         fail "Unable to clone the RVM repository, attempted both git:// and https://"
       fi
     fi
@@ -123,21 +165,30 @@ install_head()
   return 0
 }
 
-shopt -s extglob
-set -o errtrace
-set -o errexit
+# Tracing, if asked for.
+if [[ "$*" =~ --trace ]] || (( ${rvm_trace_flag:-0} > 0 ))
+then
+  set -o xtrace
+  export rvm_trace_flag=1
+fi
 
-export HOME="${HOME%%+(\/)}" # Remove trailing slashes if they exist on HOME
+# Variable initialization, remove trailing slashes if they exist on HOME
+true \
+  ${rvm_trace_flag:=0} ${rvm_debug_flag:=0} ${rvm_user_install_flag:=0}\
+  ${rvm_ignore_rvmrc:=0} HOME="${HOME%%+(\/)}"
 
-if (( ${rvm_ignore_rvmrc:=0} == 0 ))
+
+if (( rvm_ignore_rvmrc == 0 ))
 then
   for rvmrc in /etc/rvmrc "$HOME/.rvmrc"
   do
-    if [[ -f "$rvmrc" ]]
+    if [[ -s "$rvmrc" ]]
     then
       if \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
       then
-        printf "\nError: $rvmrc is for rvm settings only.\nrvm CLI may NOT be called from within $rvmrc. \nSkipping the loading of $rvmrc"
+        printf "\nError: $rvmrc is for rvm settings only.\n"
+        printf "rvm CLI may NOT be called from within $rvmrc. \n"
+        printf "Skipping the loading of $rvmrc\n"
         return 1
       else
         source "$rvmrc"
@@ -148,87 +199,65 @@ fi
 
 if [[ -z "${rvm_path:-}" ]]
 then
-  # Set the default sandboxed value.
-  # TODO: Alter the variable names to make sense
-  if [[ -z "${rvm_user_install_flag:-}" ]]
+  if (( UID == 0 ))
   then
-    if (( UID == 0 )) ||
-      [[ -n "${rvm_prefix:-}" && "${rvm_prefix:-}" != "${HOME}" ]]
-    then
-      rvm_user_install_flag=0
-    else
-      rvm_user_install_flag=1
-    fi
+    rvm_path="/usr/local/rvm"
+  else
+    rvm_path="${HOME}/.rvm"
   fi
-
-  if [[ -z "${rvm_prefix:-}" ]]
-  then
-    if (( ${rvm_user_install_flag:=0} == 0 ))
-    then
-      rvm_prefix="/usr/local"
-    elif [[ -n "$HOME" ]]
-    then
-      rvm_prefix="$HOME"
-    else
-      echo "No \$rvm_prefix was provided and "
-      echo "$(id | \sed -e's/^[^(]*(//' -e 's/).*//') has no \$HOME defined."
-      echo "Halting loading of RVM."
-      rvm_load_rvm=0
-    fi
-  fi
-
-  true "${rvm_prefix/rvm/scripts}" # Fix rvm_prefix changes, older installs.
-
-  if [[ -z "${rvm_path:-}" ]]
-  then
-    if [[ "$rvm_prefix" = "$HOME" ]]
-    then
-      rvm_path="${rvm_prefix}/.rvm"
-    else
-      rvm_path="${rvm_prefix}/rvm"
-    fi
-  fi
-
-  export rvm_path="${rvm_path%%+(\/)}"
 fi
+export HOME rvm_path
 
 # Parse CLI arguments.
-while [[ $# -gt 0 ]] ; do
-  token="$1" ; shift
+while (( $# > 0 ))
+do
+  token="$1"
+  shift
   case "$token" in
-
-    --path)
-      if [[ -n "${1:-}" ]] ; then
-        rvm_path="$1" ; shift
-      else
-        fail "--path must be followed by a path."
-      fi
-      ;;
 
     --trace)
       set -o xtrace
       export rvm_trace_flag=1
       ;;
 
+    --path)
+      if [[ -n "${1:-}" ]]
+      then
+        rvm_path="$1"
+        shift
+      else
+        fail "--path must be followed by a path."
+      fi
+      ;;
+
     --branch) # Install RVM from a given branch
-      if [[ -n "${1:-}" ]] ; then
+      if [[ -n "${1:-}" ]]
+      then
         version="head"
-        branch="$1" ; shift
+        branch="$1"
+        shift
       else
         fail "--branch must be followed by a branchname."
       fi
       ;;
 
+    --user-install)
+      rvm_user_install_flag=1
+      ;;
+
     --version)
       case "$1" in
         +([[:digit:]]).+([[:digit:]]).+([[:digit:]]))
-          version="$1" ; shift
+          version="$1"
+          shift
           ;;
         latest|stable)
-          version="latest" ; shift
+          version="latest"
+          shift
           ;;
         head|master)
-          version="head" ; shift
+          version="head"
+          shift
           branch="master"
           ;;
         *)
@@ -241,12 +270,10 @@ while [[ $# -gt 0 ]] ; do
       version="$token"
       ;;
 
-
     help|usage)
       usage
       exit 0
       ;;
-
   *)
     usage
     exit 1
@@ -257,50 +284,57 @@ done
 
 true "${version:=head}"
 
-export PS4="+ \${BASH_SOURCE##\${rvm_path:-}} : \${FUNCNAME[0]:+\${FUNCNAME[0]}()}  \${LINENO} > "
+if [[ "$rvm_path" != /* ]]
+then
+  fail "The rvm install path must be fully qualified. Tried $rvm_path"
+fi
 
 rvm_src_path="$rvm_path/src"
 rvm_archives_path="$rvm_path/archives"
 rvm_releases_url="https://rvm.beginrescueend.com/releases"
-rvm_prefix="$(dirname $rvm_path)/"
 
-for dir in  "$rvm_src_path" "$rvm_archives_path" ; do
-  [[ ! -d "$dir" ]] && mkdir -p "$dir/"
+for dir in "$rvm_src_path" "$rvm_archives_path"
+do
+  if [[ ! -d "$dir" ]]
+  then
+    mkdir -p "$dir"
+  fi
 done
 
 # Perform the actual installation, first we obtain the source using whichever
 # means was specified, if any. Defaults to head.
 case "${version}" in
-  head)
+  (head)
     install_head
     ;;
 
-  latest)
+  (latest)
     fetch_version
     install_release
     ;;
 
-  +([[:digit:]]).+([[:digit:]]).+([[:digit:]])) # x.y.z
+  (+([[:digit:]]).+([[:digit:]]).+([[:digit:]])) # x.y.z
     install_release
     ;;
-  *)
+  (*)
     fail "Something went wrong, unrecognized version '$version'"
     ;;
 esac
 
 # No matter which one we are doing we install the same way, using the RVM
 #   installer script.
+flags=()
+if (( rvm_trace_flag == 1 ))
+then
+  flags+=("--trace")
+fi
+
+if (( rvm_debug_flag == 1 ))
+then
+  flags+=("--debug")
+fi
+
 chmod +x ./scripts/install
 
-# flags=()
-# if (( ${rvm_trace_flag:-0} == 1 ))
-# then
-#   flags+=("--trace")
-# fi
-# if (( ${rvm_debug_flag:-0} == 1 ))
-# then
-#   flags+=("--debug")
-# fi
-
-# Now we yield to the RVM installer.
-exec ./scripts/install ${flags[*]} --prefix "$rvm_prefix" --path "$rvm_path"
+# Now we run the RVM installer.
+./scripts/install ${flags[*]} --path "$rvm_path"
